server:
  port: 7200

spring:
  application:
    name: merch
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: dev
  config:
    import:
      - nacos:application.yml
      - nacos:${spring.application.name}.yml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3307/cm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB