server:
  port: 4444

spring:
  application:
    name: upms
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: dev
  config:
    import:
      - nacos:application.yml
      - nacos:${spring.application.name}.yml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3307/cm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
cm:
  alipay:
    rate: 0.6 # 支付宝开放平台提现税率（当前官方设定日活量较低时为0.6%）
  wechatpay:
    rate: 0.6 # 微信开放平台提现税率（当前官方设定日活量较低时为0.6%）

file:
  bucketName: cbdFile
  local:
    enable: true
    base-path: /temp/chengda
  oss:
    enable: false
    endpoint: http://192.168.31.99:9000
    access-key: LTAI5tS6eHqYXQEYpVnhNLga
    secret-key: vdbJUelounGoq31nAa3xZj9bNoEZYr