server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      username: nacos
      password: V$cRem1J
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        namespace: cloud
        watch:
          enabled: true
        watch-delay: 1000
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: cloud
  config:
    import:
      - optional:nacos:application.yml
      - optional:nacos:${spring.application.name}.yml