server:
  port: 3000

spring:
  application:
    name: auth
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: dev
  config:
    import:
      - nacos:application.yml
      - nacos:${spring.application.name}.yml