server:
  port: 5002

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: nacos
      password: V$cRem1J
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
        namespace: cloud
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: cloud
  config:
    import:
      - nacos:application-@profiles.active@.yml
      - nacos:${spring.application.name}-@profiles.active@.yml


